# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message_spec.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='message_spec.proto',
  package='torps.ext',
  serialized_pb='\n\x12message_spec.proto\x12\ttorps.ext\"w\n\rStatusMessage\x12/\n\x06status\x18\x01 \x02(\x0e\x32\x1f.torps.ext.StatusMessage.Status\x12\x0b\n\x03msg\x18\x02 \x01(\t\"(\n\x06Status\x12\x06\n\x02OK\x10\x01\x12\x07\n\x03\x45RR\x10\x02\x12\r\n\tDATA_NEXT\x10\x03\"8\n\x11NodeSpecification\x12\n\n\x02id\x18\x01 \x02(\t\x12\x17\n\x0f\x63ongestion_dist\x18\x02 \x03(\x01\">\n\x0bLatencyInfo\x12\x0e\n\x06n1_idx\x18\x01 \x02(\r\x12\x0e\n\x06n2_idx\x18\x02 \x02(\r\x12\x0f\n\x07latency\x18\x03 \x02(\x01\"\xc5\x01\n\tCoordInit\x12\x17\n\x0cnum_networks\x18\x01 \x01(\r:\x01\x31\x12\x1f\n\x17update_interval_seconds\x18\x02 \x02(\r\x12 \n\x15ping_interval_seconds\x18\x03 \x01(\r:\x01\x33\x12/\n\tnode_data\x18\x04 \x03(\x0b\x32\x1c.torps.ext.NodeSpecification\x12+\n\x0blatency_map\x18\x05 \x03(\x0b\x32\x16.torps.ext.LatencyInfo\"J\n\nCoordinate\x12\x0f\n\x07node_id\x18\x01 \x02(\t\x12\x0b\n\x03\x64im\x18\x02 \x02(\x05\x12\r\n\x05\x65rror\x18\x03 \x02(\x01\x12\x0f\n\x07vectors\x18\x04 \x03(\x01\"H\n\x0b\x43oordUpdate\x12\x12\n\nnetwork_id\x18\x01 \x02(\r\x12%\n\x06\x63oords\x18\x02 \x03(\x0b\x32\x15.torps.ext.Coordinate\"\x9d\x01\n\x0e\x43ontrolMessage\x12\x1d\n\x04type\x18\x01 \x02(\x0e\x32\x0f.torps.ext.Type\x12\'\n\tinit_data\x18\x02 \x01(\x0b\x32\x14.torps.ext.CoordInit\x12+\n\x0bupdate_data\x18\x03 \x01(\x0b\x32\x16.torps.ext.CoordUpdate\x12\x16\n\x0eget_network_id\x18\x04 \x01(\r*%\n\x04Type\x12\x08\n\x04INIT\x10\x01\x12\x07\n\x03GET\x10\x02\x12\n\n\x06\x43OORDS\x10\x03')

_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='torps.ext.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='INIT', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GET', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='COORDS', index=2, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=786,
  serialized_end=823,
)

Type = enum_type_wrapper.EnumTypeWrapper(_TYPE)
INIT = 1
GET = 2
COORDS = 3


_STATUSMESSAGE_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='torps.ext.StatusMessage.Status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OK', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERR', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DATA_NEXT', index=2, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=112,
  serialized_end=152,
)


_STATUSMESSAGE = _descriptor.Descriptor(
  name='StatusMessage',
  full_name='torps.ext.StatusMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='torps.ext.StatusMessage.status', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='msg', full_name='torps.ext.StatusMessage.msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _STATUSMESSAGE_STATUS,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=33,
  serialized_end=152,
)


_NODESPECIFICATION = _descriptor.Descriptor(
  name='NodeSpecification',
  full_name='torps.ext.NodeSpecification',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='torps.ext.NodeSpecification.id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='congestion_dist', full_name='torps.ext.NodeSpecification.congestion_dist', index=1,
      number=2, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=154,
  serialized_end=210,
)


_LATENCYINFO = _descriptor.Descriptor(
  name='LatencyInfo',
  full_name='torps.ext.LatencyInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='n1_idx', full_name='torps.ext.LatencyInfo.n1_idx', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='n2_idx', full_name='torps.ext.LatencyInfo.n2_idx', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='latency', full_name='torps.ext.LatencyInfo.latency', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=212,
  serialized_end=274,
)


_COORDINIT = _descriptor.Descriptor(
  name='CoordInit',
  full_name='torps.ext.CoordInit',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='num_networks', full_name='torps.ext.CoordInit.num_networks', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='update_interval_seconds', full_name='torps.ext.CoordInit.update_interval_seconds', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ping_interval_seconds', full_name='torps.ext.CoordInit.ping_interval_seconds', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=3,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='node_data', full_name='torps.ext.CoordInit.node_data', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='latency_map', full_name='torps.ext.CoordInit.latency_map', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=277,
  serialized_end=474,
)


_COORDINATE = _descriptor.Descriptor(
  name='Coordinate',
  full_name='torps.ext.Coordinate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='node_id', full_name='torps.ext.Coordinate.node_id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dim', full_name='torps.ext.Coordinate.dim', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='error', full_name='torps.ext.Coordinate.error', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vectors', full_name='torps.ext.Coordinate.vectors', index=3,
      number=4, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=476,
  serialized_end=550,
)


_COORDUPDATE = _descriptor.Descriptor(
  name='CoordUpdate',
  full_name='torps.ext.CoordUpdate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='network_id', full_name='torps.ext.CoordUpdate.network_id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='coords', full_name='torps.ext.CoordUpdate.coords', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=552,
  serialized_end=624,
)


_CONTROLMESSAGE = _descriptor.Descriptor(
  name='ControlMessage',
  full_name='torps.ext.ControlMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='torps.ext.ControlMessage.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='init_data', full_name='torps.ext.ControlMessage.init_data', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='update_data', full_name='torps.ext.ControlMessage.update_data', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='get_network_id', full_name='torps.ext.ControlMessage.get_network_id', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=627,
  serialized_end=784,
)

_STATUSMESSAGE.fields_by_name['status'].enum_type = _STATUSMESSAGE_STATUS
_STATUSMESSAGE_STATUS.containing_type = _STATUSMESSAGE;
_COORDINIT.fields_by_name['node_data'].message_type = _NODESPECIFICATION
_COORDINIT.fields_by_name['latency_map'].message_type = _LATENCYINFO
_COORDUPDATE.fields_by_name['coords'].message_type = _COORDINATE
_CONTROLMESSAGE.fields_by_name['type'].enum_type = _TYPE
_CONTROLMESSAGE.fields_by_name['init_data'].message_type = _COORDINIT
_CONTROLMESSAGE.fields_by_name['update_data'].message_type = _COORDUPDATE
DESCRIPTOR.message_types_by_name['StatusMessage'] = _STATUSMESSAGE
DESCRIPTOR.message_types_by_name['NodeSpecification'] = _NODESPECIFICATION
DESCRIPTOR.message_types_by_name['LatencyInfo'] = _LATENCYINFO
DESCRIPTOR.message_types_by_name['CoordInit'] = _COORDINIT
DESCRIPTOR.message_types_by_name['Coordinate'] = _COORDINATE
DESCRIPTOR.message_types_by_name['CoordUpdate'] = _COORDUPDATE
DESCRIPTOR.message_types_by_name['ControlMessage'] = _CONTROLMESSAGE

class StatusMessage(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _STATUSMESSAGE

  # @@protoc_insertion_point(class_scope:torps.ext.StatusMessage)

class NodeSpecification(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _NODESPECIFICATION

  # @@protoc_insertion_point(class_scope:torps.ext.NodeSpecification)

class LatencyInfo(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LATENCYINFO

  # @@protoc_insertion_point(class_scope:torps.ext.LatencyInfo)

class CoordInit(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _COORDINIT

  # @@protoc_insertion_point(class_scope:torps.ext.CoordInit)

class Coordinate(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _COORDINATE

  # @@protoc_insertion_point(class_scope:torps.ext.Coordinate)

class CoordUpdate(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _COORDUPDATE

  # @@protoc_insertion_point(class_scope:torps.ext.CoordUpdate)

class ControlMessage(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CONTROLMESSAGE

  # @@protoc_insertion_point(class_scope:torps.ext.ControlMessage)


# @@protoc_insertion_point(module_scope)
